apiVersion: v1
kind: Service
metadata:
  name: api-svc
  labels:
    component: api
    app: todo
spec:
  ports:
  - port: 8081
    targetPort: 8081
    name: api
  selector:
    app: todo
    component: api
  type: ClusterIP
